console.log("Hello");
console.log(123);
console.log(true);
const greeting = 'Hello';
console.log(greeting);
console.log([1,2,3,4,5]);
console.log({a:1, b:2});
console.table({a:1, b:3});
console.error(`This is some error`);
console.clear();
console.warn(`This is a warning`);
console.time(`Hello`);
console.timeEnd(`Hello World`);